# Do not use Kong Ingress Controller
ingressController:
  enabled: false
   
image:
  repository: kong/kong-gateway
   
secretVolumes:
  - kong-cluster-ca
  - kong-cluster
   
env:
  role: control_plane
  
  # PKI Mode mTLS
  cluster_mtls: pki
  cluster_ca_cert: /etc/secrets/kong-cluster-ca/tls.crt
  cluster_cert: /etc/secrets/kong-cluster/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster/tls.key
   
  database: postgres
  pg_database: kong
  pg_user: kong
  pg_password: demo123
  pg_host: kong-cp-db-rw.kong.svc.cluster.local
  pg_ssl: "on"
  pg_ssl_version: tlsv1_3
   
  # Kong Manager
  password: admin
  admin_gui_url: http://localhost:8002
  admin_gui_api_url: http://localhost:8001
  rbac: "off"
   
# Enterprise functionality
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  rbac:
    enabled: false    

# The control plane serves the Admin API
admin:
  enabled: true
  http:
    enabled: true
   
# Clustering endpoints are required in hybrid mode
cluster:
  enabled: true
  tls:
    enabled: true
   
clustertelemetry:
  enabled: true
  tls:
    enabled: true
   
manager:
  enabled: true
  http:
    enabled: true
  tls:
    enabled: false
   
# These roles will be served by different Helm releases
proxy:
  enabled: false