apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kong-cp-db
  namespace: kong
spec:
  instances: 1

  bootstrap:
    initdb:
      database: kong
      owner: kong
      secret:
        name: kong-db-secret

  storage:
    size: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
  namespace: kong
type: Opaque
stringData:
  username: kong
  password: demo123
