version: "3"

tasks:
  install:
    cmds:
      - task: init
      - task: create-secrets
      - task: install-pg
      - task: install-cp
      - task: install-dp

  init:
    desc: "Setup Helm repos and namespace"
    cmds:
      - helm repo add kong https://charts.konghq.com
      - helm repo update
      - kubectl create namespace kong --dry-run=client -o yaml | kubectl apply -f -

  create-secrets:
    desc: "Create Kubernetes secrets for license and PKI"
    cmds:
      - kubectl create secret generic kong-enterprise-license --from-file=license=${HOME}/.kong-license-data/license.json -n kong --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret tls kong-cluster --cert=certs/kong_clustering.crt --key=certs/kong_clustering.key -n kong
      - kubectl create secret generic kong-cluster-ca --from-file=tls.crt=certs/kong_clustering_ca.crt -n kong
      - kubectl create secret generic kong-dp-cert --from-file=dp.crt=certs/kong_clustering_client.crt --from-file=dp.key=certs/kong_clustering_client.key --from-file=ca.crt=certs/kong_clustering_ca.crt -n kong

  install-pg:
    cmds:
      - helm repo add cnpg https://cloudnative-pg.github.io/charts
      - helm upgrade --install cnpg -n cnpg --create-namespace cnpg/cloudnative-pg
      - kubectl apply -f values-pg.yaml

  install-cp:
    desc: "Deploy Control Plane with PKI mTLS"
    cmds:
      - helm upgrade --install kong-cp kong/kong -n kong --values values-cp.yaml --set image.tag=${KONG_TAG:-3.12}
      - kubectl wait deployment/kong-cp-kong --for=condition=available --timeout=300s -n kong

  install-dp:
    desc: "Deploy Data Plane with PKI mTLS"
    cmds:
      - helm upgrade --install kong-dp kong/kong -n kong --values values-dp.yaml --set image.tag=${KONG_TAG:-3.12}
      - kubectl wait deployment/kong-dp-kong --for=condition=available --timeout=300s -n kong

  clean:
    cmds:
      - kubectl delete namespace kong